services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        USERNAME: rosuser
    image: mi_proyecto_ros2:latest
    container_name: ros2_dev_2
    stdin_open: true
    tty: true

    # Red: modo bridge (portable en Docker Desktop)
    networks:
      - rosnet

    volumes:
      - ./src:/ros2_ws/src
      - ./maps:/ros2_ws/maps

      - ros2_build:/ros2_ws/build
      - ros2_install:/ros2_ws/install
      - ros2_log:/ros2_ws/log
      # X11 forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      - ROS_DOMAIN_ID=0
      - USER=rosuser
      - HOME=/home/rosuser
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    # Si necesitas GUI en Windows, NO uses /tmp/.X11-unix.
    # Te lo dejo preparado para cuando me pases tu Dockerfile y me digas si usas WSLg / XServer.
    # environment:
    #   - DISPLAY=${DISPLAY}

volumes:
  ros2_build:
  ros2_install:
  ros2_log:


networks:
  rosnet:
    driver: bridge
